### ISSUE TITLE
Unexpected token in json/nothing displayed

### ISSUE THREAD

**Issue by DanielWeeber** [LukeSkywalker92/MMM-SoccerLiveScore#4]
Config is the same as in your Readme

First start:

0|mm       | SyntaxError: Unexpected token u in JSON at position 0
0|mm       |     at JSON.parse (<anonymous>)
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/MMM-SoccerLiveScore/node_helper.js:68:37)
0|mm       |     at self.callback (/home/pi/MagicMirror/node_modules/request/request.js:188:22)
0|mm       |     at emitOne (events.js:96:13)
0|mm       |     at Request.emit (events.js:191:7)
0|mm       |     at Request.onRequestError (/home/pi/MagicMirror/node_modules/request/request.js:884:8)
0|mm       |     at emitOne (events.js:96:13)
0|mm       |     at ClientRequest.emit (events.js:191:7)
0|mm       |     at TLSSocket.socketErrorListener (_http_client.js:358:9)
0|mm       |     at emitOne (events.js:96:13)

**Comment by Quarx64** [comment]
Kommt manchmal vor, wenn gerade keine verwertbaren Daten geliefert werden. Einfach eine Weile warten (bis zum eingestellten Timeout), dann geht es wieder.

**Comment by husoseli15** [comment]
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-SoccerLiveScore/node_helper.js:68:37)
    at self.callback (/home/pi/MagicMirror/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/pi/MagicMirror/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)

Same issue here. It worked earlier today and now this.
