### ISSUE TITLE
Error when try to update

### ISSUE THREAD

**Issue by ezar** [LukeSkywalker92/MMM-SoccerLiveScore#5]
0|MagicMir | TypeError: Cannot read property 'length' of undefined
0|MagicMir |     at Request._callback (/home/pi/MagicMirror/modules/MMM-SoccerLiveScore/node_helper.js:117:55)
0|MagicMir |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:186:22)
0|MagicMir |     at emitTwo (events.js:106:13)
0|MagicMir |     at Request.emit (events.js:191:7)
0|MagicMir |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1163:10)
0|MagicMir |     at emitOne (events.js:96:13)
0|MagicMir |     at Request.emit (events.js:188:7)
0|MagicMir |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1085:12)
0|MagicMir |     at IncomingMessage.g (events.js:286:16)
0|MagicMir |     at emitNone (events.js:91:20)

**Comment by terenc3** [comment]
It seems that the response body changed since the function was implemend. There is now a table and a legend section.  I could fix this by adding the following to node_helper.js line 117

`if (data.data[i].type !== 'table') {
    continue;
}`

**Comment by terenc3** [comment]
Also need to replace node_helper.js line 151 - 159 with
```
for(var i = 0; i < data.length; i++) {
    if (data[i].type === 'table') {
        self.sendSocketNotification('TABLE', {
            leagueId: leagueId,
            table: data[i].table
        });
        setTimeout(function () {
            self.getTable(leagueId);
        }, refreshTime);
        return;
    }
}
```
to get thet table working again

**Comment by 42SK** [comment]
@terenc3 
I have not yet tested your fix, but your explanation seems quite reasonable.
Perhaps you should open a pull request?

**Comment by LukeSkywalker92** [comment]
Yes. Please open a request if everything is fine. I don’t have time to watch over it, but I will merge it.
