### ISSUE TITLE
No logo

### ISSUE THREAD

**Issue by Exkilex** [LukeSkywalker92/MMM-SoccerLiveScore#6]
Hello

i have the follow behavier

/home/pi/.pm2/logs/mm-error-0.log last 15 lines:
0|mm       |     at Request.emit (events.js:188:7)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1085:12)
0|mm       |     at IncomingMessage.g (events.js:286:16)
0|mm       |     at emitNone (events.js:91:20)
0|mm       | TypeError: Cannot read property 'length' of undefined
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/MMM-SoccerLiveScore/node_helper.js:117:55)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:186:22)
0|mm       |     at emitTwo (events.js:106:13)
0|mm       |     at Request.emit (events.js:191:7)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1163:10)
0|mm       |     at emitOne (events.js:96:13)
0|mm       |     at Request.emit (events.js:188:7)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1085:12)
0|mm       |     at IncomingMessage.g (events.js:286:16)
0|mm       |     at emitNone (events.js:91:20)

![soccer](https://user-images.githubusercontent.com/35780018/35352829-1a44b118-013d-11e8-9bfa-1aa56b581833.PNG)

**Comment by 42SK** [comment]
I'm also affected by this bug.
Judging by the error log, I'd assume this is probably related to issue #5.

**Comment by tehfunky** [comment]
Same problem here .. it works with maximum 8 teams. You can try it with ID 9 (German Cup).

**Comment by Schmady** [comment]
Same here. Noone a idea how to fix this?

**Comment by marphi1602** [comment]
try to disable the icons by adding that to your cfg.
showLogos: false,

**Comment by Schmady** [comment]
> showLogos: false,

I know that this is working, but this is not the solution I'm looking for :-)
